# GET /api/test/user HTTP/1.1
# Host: 127.0.0.1:8080
# x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjI2NmJjMTM4YzU0OGJlYWNlZTFhZiIsImlhdCI6MTY1MDYxNjM4NSwiZXhwIjoxNjUwNzAyNzg1fQ.Le4KRtbHrvwf7tMs65R3gGrkuxPBUQUoBp2waW46Oko


### register
GET http://127.0.0.1:8080/api/test/user HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODM5N2QzMjZhYjlkZWRiOTMwNzI0NCIsImlhdCI6MTY1Mjc5MTMzOSwiZXhwIjoxNjUyNzk0OTM5fQ.ntMIIdpO3J11-vzXr6eacvfPbzDumMWj6iLLXttjdE8