GET /api/auth/refreshtoken HTTP/1.1
Host: 127.0.0.1:8080
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjI2NmJjMTM4YzU0OGJlYWNlZTFhZiIsImlhdCI6MTY1MDYxODE4MiwiZXhwIjoxNjUwNzA0NTgyfQ.68YmANuKRhfKGKc0301BIsYSr0GtQTHxZYrp8azDvvc